enum HHRPCEnum
{
	// Server RPC
	RPC_CLIENT_UPDATE_TOP = -194094888,
	RPC_CLIENT_SHOW_END_SCREEN,
	RPC_CLIENT_HIDE_END_SCREEN,
	RPC_CLIENT_UPDATE_MAIN_SCREEN_TIMER,
	RPC_SHOW_ADMIN_FUN_MESSAGE,

	// CLient RPC
	RPC_SELECT_MAP_1,
	RPC_SELECT_MAP_2,
	RPC_SELECT_MAP_3,
	RPC_SELECT_CURRENT_MAP
}